fossasia/susi_firefoxbot

.travis.yml
=> add test in .travis.yml

.github/ISSUE_TEMPLATE.md, .github/PULL_REQUEST_TEMPLATE.md
Fixed https://github.com/fossasia/susi_firefoxbot/issues/11
=> Added Templates for issue and pull request

src/chatbot.html, src/scripts/main.js
Fixed issue https://github.com/fossasia/susi_firefoxbot/issues/9
- Autofocus when extension opens
=> Add autofocus when extension pops up

src/index.css
Issue no. #18 
Fixes issue #18:Make send icon attractive
Colour of send button icon matches with colour of send button icon in https://chat.susi.ai/
=> Fixes issue #18:Make send icon attractive

src/scripts/main.js
added regexp to check for a hyperlink and place it inside <a> tags.
=> Fix issue #26 - add hyperlink to the search result

src/index.css, src/scripts/main.js
Fixes issue #28
-Added support for table type of response from server
-Handles table type and renders a table 
-Also, detects for any hyperlinks and adds <a> tag.
=> Add support for table type of response from server - fixes #28

src/chatbot.html
Add hyperlink to susi.ai on clicking SUSI logo.
Fixes #34
=> chatbot.html: Add hyperlink

src/chatbot.html, src/index.css, src/manifest.json, src/scripts/main.js
Fixes issue #27 
- Add map from leaflet library
- Get user's location and send to server
- Support anchor type of response
- Sync map with browser history
- Add appropriate permissions in manifest file
(Please clear cache before testing this)
=> Support map and anchor type of responses - fixes #27

src/chatbot.html
Fixes issue #[48]
- 
Change the .SVg to .svg in this line of susi_firefoxbot/src/chatbot.html
from "src="images/settings.SVg">"
to  "src="images/settings.svg">
=> Fixed typo in chatbot.html #48

src/scripts/main.js
Fixes issue #37 
* add function loadMoreMessages that checks if the user has scrolled to the top and loads older messages.
* add variable numberOfMessagesToLoad that gives the number of messages to load initially and each time the user scrolls up.
=> Fix issue #37 - fix the lag when popup is opened

src/index.js, src/scripts/options.js, src/settings.css, src/settings.html
Fixes issue #63 
- Add clear message history option button in settings
- Ask for confirmation before clearing
=> Add clear message history button - fixes #63

README.md
Fixes issue #[65]
- Adds communication channel to readme
https://github.com/ParthS007/susi_firefoxbot
=> Fixes#65 Adds communication channel to readme

src/scripts/options.js, src/settings.css, src/settings.html
Fixes issue #41 
- Add login form in settings
-Get access token
-Use access token to retrieve settings
-If theme setting available, update the theme
=> Add login feature - fixes #41

src/scripts/options.js
Fixes issue #73 
* modify clearMessagesHistory function in options.js
=> Fix #73 - prevent the theme from getting cleared

src/scripts/options.js, src/settings.html
Fixes issue #69 
- Use access token to retrieve chat history
- Clear the local message history
- Populate query and response in the cache
=> Add chat history retrieval after log in - fixes #69

src/chatbot.html, src/index.css, src/scripts/main.js, src/scripts/options.js, src/settings.css, src/settings.html
Fixes issue #71 
- Show the user's email address in the header section when logged in.
- Show Logout option when logged in
- Clear messages when logged out
=> Show logged in email and logout option - fix #71

src/scripts/main.js, src/scripts/options.js
Fixes issue #77
- Store access token in browser memory
- Maintain state for login
- If logged append access token in url
=> Use access token when user is loggged in - fixes #77

src/chatbot.html, src/manifest.json, src/scripts/background.js, src/scripts/main.js
Fixes issue #67 
- Add a background script
- Add contextMenu permission in manifest file
- Add a context menu "Ask SUSI"
- Open SUSI popup and search for the selected text
(the popup will open only on firefox 57 and above, see [here](https://developer.mozilla.org/en-US/Add-ons/WebExtensions/API/browserAction/openPopup))
=> Add context menu on selection and right click - fix #67

src/scripts/main.js
Fixes issue #59
- Changed map marker text
=> Change map marker text - fixes #59

src/index.css, src/scripts/main.js
Fixes issue #40 
- Added pattern to identify image link and replace with img tag
- Added required css to support img inside chat bubble
=> Add image support - fixes #40

src/scripts/background.js
Fixes issue #93
- Add selection text in context menu title
=> Add selected text in context menu title - fixes 93

src/scripts/options.js, src/settings.html
Fixes issue #84 
- Add change password forms
- Validate on submit, and send request to the server
- Show appropriate message to the user
- Make a separate logged-in block, and logged-out block to display settings in Settings page
=> Fix #84 - Add Change Password option

src/css/settings.css, src/manifest.json, src/scripts/options.js, src/settings.html
Fixes issue #83 
- Add font awesome cdn
- Show loading icon while logging in
- Show loading icon while changing password
- Check for empty email or password on submission
- Add horizontal lines under main headings
- Auto save theme on changing
- Change the background color of clear history button to red
=> Fix #83 - Improve UI in Settings page

src/index.css, src/scripts/main.js, src/settings.css
Fixes issue #99
- Add indication if chat history is empty
=> Add indication if chat history is empty - fix #99

src/scripts/options.js
Fixes issue #89 
- When the user changes the theme make an API call to change settings value on the server.
- Notify user if theme updated successfully.
=> Sync theme settings if user is logged in - fix #89

src/chatbot.html, src/index.css, src/scripts/main.js
Fixes issue #102
- Show the scroll icon if the user scroll above
- Hide the scroll icon if the user scroll to the bottom
- On clicking the scroll icon, take user to the bottom of the chat.
=> Fix #102 - show icon to jump to bottom of chat

src/index.css
Fixes issue #103 
- Add max height property to table message
- Enable scrolling inside table
=> Fix #103 - limit the height of table

.github/ISSUE_TEMPLATE.md
Fixes #113 
-  Commented out suggestions statements.
=> Comment out suggestions in Issue Template

.github/PULL_REQUEST_TEMPLATE.md
Fixes #114 
- Changed PULL_REQUEST_TEMPLATE to close issues automatically.
=> Updates PR Template

src/scripts/main.js
Fixes #128 
@mariobehling  @tstreamDOTh  Please review this .
=> Fetching Videos Similar to Susi_Chromebot

src/css/settings.css, src/scripts/options.js, src/settings.html
Fixes #125 
- It indicate atleast 6 character limit while changing the password.
- Till the length of character is at least 6 the `change password` button will not work.
=> Added minimum password limit in change password limit

src/css/index.css, src/scripts/main.js, src/scripts/options.js, src/settings.html
Adds color selector for #134
- Adds in two color selectors in the settings page, one for the top bar and one for the background
- Allows the following colors, with more colors easily added: default (uses light/dark theme), red, blue, black, brown, green
=> Added Color Selectors

src/chatbot.html, src/css/index.css, src/scripts/main.js
Fixes #136 
- Added scroll to top functionality
=> Added scroll top button

src/chatbot.html, src/scripts/main.js
Fixes #132
- Adding Login And Logout Option inside drop down menu
=> Fix-132 Adding Login And Logout Option inside dropdown menu

src/css/settings.css, src/scripts/options.js, src/settings.html
Fixes #140 
- Eye added in password field of login form. This will enable user to show/hide password.
about: addons
=> eye added for password field of login form

src/chatbot.html, src/css/index.css
Fixes #151
Here is a before and after image of the change.
=> Fix topbar

src/chatbot.html
=> Span tag closed, typo fixed in chatbot.html

src/css/settings.css, src/scripts/options.js, src/settings.html
Fixes #165 
Added eye in the password field.
=> Added eye in the password field.

src/chatbot.html, src/css/index.css
Fixes #161 
Scrolltop button for chat added
GIF:-
=> Scrolltop button added

src/scripts/background.js
=> context item added(Find on map)
